// <auto-generated by="the Blazor I18n Text compiler" />
namespace CoolStore.UI.Blazor.I18nText
{
    public partial class MyText : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Category"</summary>
        public string HomePage_Category;

        /// <summary>"Description"</summary>
        public string HomePage_Description;

        /// <summary>"Image"</summary>
        public string HomePage_Image;

        /// <summary>"Inventory Location"</summary>
        public string HomePage_InventoryLocation;

        /// <summary>"Name"</summary>
        public string HomePage_Name;

        /// <summary>"Price"</summary>
        public string HomePage_Price;

        /// <summary>"Description"</summary>
        public string InventoryPage_Description;

        /// <summary>"Location"</summary>
        public string InventoryPage_Location;

        /// <summary>"Website"</summary>
        public string InventoryPage_Website;
    }
}
